version: 2.1

orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build:server
            - run: npm run build:client
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over ssh
          command: ssh $SSH_USER@$SSH_HOST "cd inventory-v2/ssr-webpack/; git fetch; git reset --hard $CIRCLE_SHA1; export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v13.11.0/bin/; npm ci && npm run build:client && npm run build:server && sudo systemctl restart node-inventory-app"
workflows:
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
