export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_BIN_DATA = "SET_BIN_DATA";
export const SET_UNIQ_DATA = "SET_UNIQ_DATA";
export const SET_SKU_DATA = "SET_SKU_DATA";
export const SET_BATCH_DATA = "SET_BATCH_DATA";
